name: Wish or idea / Wunsch oder Idee
description: Suggest a new feature or an improvement / Eine neue Funktion oder Verbesserung vorschlagen
labels: [enhancement]
body:
  - type: textarea
    id: idee
    attributes:
      label: "What would you like? / Was wünschst du dir?"
      description: "And what do you need it for? / Und wofür brauchst du es?"
    validations:
      required: true
  - type: dropdown
    id: einsatz
    attributes:
      label: "Use / Einsatzzweck"
      options:
        - Picture frame / Bilderrahmen
        - TV / Fernseher
        - Both / Beides
        - Other / Anderes
